# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Robin
tagline:          'My blog
description:      'My first personal blog'
url:              http://robingg.github.io

author:
  name:           'Robin.G'
  url:            https://robingg.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
