# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Robin'
tagline:          'Hi, there'
description:      'Write Elegant Code.'
url:              http://robingg.github.io

author:
  name:           'Robin.G'
  url:            https://robingg.github.io

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon

gems:             [jekyll-paginate]
